# Auto-generated by ansys_s11_bridge.py
# Runs inside Ansys Electronics Desktop / HFSS IronPython.

import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop.RestoreWindow()

oDesktop.OpenProject('C:\\Users\\rikhi\\Desktop\\HFSS_WORKING_TEMP\\Project_Working.aedt')
oProject = oDesktop.SetActiveProject('Project_Working')
oDesign = oProject.SetActiveDesign('HFSSDesign1')

# No variable updates requested

# Run the generated WGS candidate geometry script.
execfile('c:\\Users\\rikhi\\Downloads\\WGS_Antenna\\WGS_Antenna\\current_candidate.py')

# Re-select the project and design after candidate generation.
oProject = oDesktop.SetActiveProject('Project_Working')
oDesign = oProject.SetActiveDesign('HFSSDesign1')

oDesign.AnalyzeAll()

oModule = oDesign.GetModule("ReportSetup")

# Export the S11 frequency sweep.
oModule.ExportToFile('Terminal S Parameter Plot1', 'C:\\Users\\rikhi\\Desktop\\s11_export.csv', False)

# Export Gain Plot1:
# Theta versus dB(GainTotal) at 2.4 GHz and Phi = 0 degrees.
oModule.ExportToFile('Gain Plot1', 'C:\\Users\\rikhi\\Desktop\\gain_export.csv', False)

# Save disabled
oDesktop.QuitApplication()
